- name: Create dir Sample
  hosts: all
  vars:
    dir1: /home/usr_srv_gitlabci_adm/ramon
    dir2: "{{ ansible_hostname }}"
  tasks:
    - name: Crea directorio
      file:
        path: "{{ dir1 }}/{{ dir2 }}"
        state: directory
  debug:
        msg: "Se ha creado la ruta {{ dir1 }}/{{ dir2 }}"

